name: Generate DrawIO Images

env:
  DRAW_IO_DIR: "draw.io"

on:
  push:
    paths:
      - draw.io/**.drawio

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate architecture image from drawio
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # reference: https://github.com/marketplace/actions/draw-io-export-action
    - name: Generate SVG Images
      uses: rlespinasse/drawio-export-action@v2
      with:
        format: svg
        path: ${{ env.DRAW_IO_DIR }}
        output: .
        remove-page-suffix: true

    - name: Push Local Changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: "Generate SVG files for draw.io diagrams"
        branch: ${{ github.head_ref }}
